### ISSUE TITLE
Give processed vocabs a class

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/wordpiece#10]
The returned vocab is a named integer vector with an `is_cased` attribute. That feels like it should be a subclass of integer. Set up proper constructors and whatnot, or at least add a "wordpiece_vocabulary" class onto it or something along those lines (I recommend including "wordpiece" cuz we'll likely have other vocabularies in other packages that use slightly different rules).

**Comment by jonathanbratt** [comment]
do we just want to include something like this?
`class(vocab) <- c("wordpiece_vocabulary", class(vocab))`
...or maybe use `structure`, since we're also setting an attribute?

**Comment by jonthegeek** [comment]
Use structure. But also read through https://adv-r.hadley.nz/s3.html#s3-constructor that stuff first and consider something a bit more structured. is_vocab() might go along with this ticket? Think about it at least.
