### ISSUE TITLE
Add a mini vocab file in inst

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/wordpiece#8]
I'll have to dig into R-pkgs notes to remember how to do this, but we should include a mini vocab.txt in the package, and then load *that* for examples. That way we won't have to dontrun all our examples, which CRAN doesn't like (plus that way we can show people how it works).

**Comment by jonathanbratt** [comment]
we do currently have a super mini vocab.txt in the testing dir, btw.

**Comment by jonthegeek** [comment]
https://r-pkgs.org/data.html#data-extdata
Ok, `inst\extdata` is built for this case: "If you want to show examples of loading/parsing raw data, put the original files in inst/extdata."

readr has a function for reading examples in but I think that's overkill: https://readr.tidyverse.org/reference/readr_example.html

We should be able to just use system.file in our examples, I think.
