### ISSUE TITLE
Fail louder in load_vocab

### ISSUE THREAD

**Issue by jonthegeek** [jonathanbratt/wordpiece#9]
If a vocab is empty, we return `integer(0)` from `load_vocab`. That will fail in the rest of the package. EITHER return it as an actual empty vocab (with the rest of the bells and whistles), or, more likely, throw an error.

**Comment by jonathanbratt** [comment]
Thinking about this... loading an empty vocab is one of the less likely failure modes we'd encounter. It's also possible that someone would try to read a badly formatted vocabulary (or a non-vocab text file). Currently, this also "works" without any messaging. Would it make sense to do some other sanity checks on the vocab, such as:
 - non-empty vocab
 - no whitespace in tokens
 - no repeated tokens
 - anything else?

We could then throw an error if the checks don't pass.

**Comment by jonthegeek** [comment]
That sounds correct. Something something character encoding maybe?
